// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB16AlUKy-gN6C_aEfWcmiQ03ToTshOYgo',
    appId: '1:200998447423:web:84ac0d4dff25ddfb580b8a',
    messagingSenderId: '200998447423',
    projectId: 'mytracker-5251a',
    authDomain: 'mytracker-5251a.firebaseapp.com',
    storageBucket: 'mytracker-5251a.firebasestorage.app',
    measurementId: 'G-JHGLLMRLNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE0IJNxnEyM9VAsDaYDVx_vaKgr9Lp9oY',
    appId: '1:200998447423:android:de2be8680691c404580b8a',
    messagingSenderId: '200998447423',
    projectId: 'mytracker-5251a',
    storageBucket: 'mytracker-5251a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB16AlUKy-gN6C_aEfWcmiQ03ToTshOYgo',
    appId: '1:200998447423:web:eb0391bd4c7588dc580b8a',
    messagingSenderId: '200998447423',
    projectId: 'mytracker-5251a',
    authDomain: 'mytracker-5251a.firebaseapp.com',
    storageBucket: 'mytracker-5251a.firebasestorage.app',
    measurementId: 'G-LB1WYQDJNK',
  );
}
